import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToasterProvider from "./providers/ToasterProvider";


export const metadata: Metadata = {
  title: "Car Zone Auction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <ToasterProvider/>
         <NavBar/>
         {children}
        </body>
    </html>
  );
}
